### ISSUE TITLE
Regressions when compared to the previous build system

### ISSUE THREAD

**Issue by marekjez86** [notofonts/Noto-Arabic#4]
I have packaged few pdf files which compared the test file outputs (created using fontdiff) there were few regressions related to diacritic positioning (see darker green [that's the newest build from this directory], reddish is the previous font -- not every darker green [darker color indicates more serious difference] is an error but you'll see some)

[regressions.zip](https://github.com/notofonts/Noto-Arabic/files/6674247/regressions.zip)

I'd like to find solution to these while maintaining the new structure that builds a single variable file with three axis: weight, width, VLHT

**Comment by moyogo** [comment]
With #5 the only differences that show in fontdiff PDFs are:
- the modified uni0773, uni0774 that are now tall in Noto Naskh Arabic but remain short in Noto Naskh Arabic UI 
- the modified alif and final alif in all composite glyphs, this is one node removed or added for interpolation compatibility
- the Urdu numbers in the relevant languages in Noto Naskh Arabic UI
- the three dots in uni06B8, uni06B8.fina, uni06D1, uni06D1.fina are now a component of uniFBB9.restricted instead of a scaled component of uniFBB9 which may produce a 1 unit rounding difference
